{"message": "Debug üzenet", "timestamp": "2024-11-19T23:11:57.163350+01:00", "level": "DEBUG", "logger": "logging_6", "module": "logging_6", "function": "main", "line": 38, "thread_name": "MainThread"}
{"message": "Info üzenet", "timestamp": "2024-11-19T23:11:57.163350+01:00", "level": "INFO", "logger": "logging_6", "module": "logging_6", "function": "main", "line": 39, "thread_name": "MainThread", "x1": 1, "x2": "ez az x2"}
{"message": "Warning üzenet", "timestamp": "2024-11-19T23:11:57.163350+01:00", "level": "WARNING", "logger": "logging_6", "module": "logging_6", "function": "main", "line": 40, "thread_name": "MainThread", "x1": 1, "x2": "ez az x2"}
{"message": "Error üzenet", "timestamp": "2024-11-19T23:11:57.163350+01:00", "level": "ERROR", "logger": "logging_6", "module": "logging_6", "function": "main", "line": 41, "thread_name": "MainThread"}
{"message": "Critical üzenet", "timestamp": "2024-11-19T23:11:57.163350+01:00", "level": "CRITICAL", "logger": "logging_6", "module": "logging_6", "function": "main", "line": 42, "thread_name": "MainThread"}
{"message": "Exception üzenet\nTraceback (most recent call last):\n  File \"h:\\DADY\\rend\\konyvtarak\\2024\\241106_1319_python_logging\\python_logging\\logging_6.py\", line 44, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2024-11-19T23:11:57.163350+01:00", "level": "ERROR", "logger": "logging_6", "module": "logging_6", "function": "main", "line": 46, "thread_name": "MainThread"}
