{"message": "Debug uzenet", "timestamp": "2024-11-13T17:56:50.793176+01:00", "level": "DEBUG", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 128, "thread_name": "MainThread"}
{"message": "Info uzenet", "timestamp": "2024-11-13T17:56:50.793176+01:00", "level": "INFO", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 129, "thread_name": "MainThread"}
{"message": "Warning üzenet", "timestamp": "2024-11-13T17:56:50.808784+01:00", "level": "WARNING", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 130, "thread_name": "MainThread"}
{"message": "Error üzenet", "timestamp": "2024-11-13T17:56:50.824422+01:00", "level": "ERROR", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 131, "thread_name": "MainThread"}
{"message": "Critical uzenet", "timestamp": "2024-11-13T17:56:50.846298+01:00", "level": "CRITICAL", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 132, "thread_name": "MainThread"}
{"message": "Exception uzenet", "timestamp": "2024-11-13T17:56:50.885254+01:00", "exc_info": "Traceback (most recent call last):\n  File \"h:\\DADY\\rend\\konyvtarak\\2024\\241106_1319_python_logging\\python_logging\\logging_4.py\", line 134, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "level": "ERROR", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 136, "thread_name": "MainThread"}
{"message": "Debug üzenet", "timestamp": "2024-11-13T17:57:38.302343+01:00", "level": "DEBUG", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 128, "thread_name": "MainThread"}
{"message": "Info üzenet", "timestamp": "2024-11-13T17:57:38.333591+01:00", "level": "INFO", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 129, "thread_name": "MainThread"}
{"message": "Warning üzenet", "timestamp": "2024-11-13T17:57:38.349202+01:00", "level": "WARNING", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 130, "thread_name": "MainThread"}
{"message": "Error üzenet", "timestamp": "2024-11-13T17:57:38.376109+01:00", "level": "ERROR", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 131, "thread_name": "MainThread"}
{"message": "Critical üzenet", "timestamp": "2024-11-13T17:57:38.398365+01:00", "level": "CRITICAL", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 132, "thread_name": "MainThread"}
{"message": "Exception üzenet", "timestamp": "2024-11-13T17:57:38.425061+01:00", "exc_info": "Traceback (most recent call last):\n  File \"h:\\DADY\\rend\\konyvtarak\\2024\\241106_1319_python_logging\\python_logging\\logging_4.py\", line 134, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "level": "ERROR", "logger": "logging_4", "module": "logging_4", "function": "main", "line": 136, "thread_name": "MainThread"}
