{"message": "Debug üzenet", "timestamp": "2024-11-14T11:24:58.705018+01:00", "level": "DEBUG", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 76, "thread_name": "MainThread"}
{"message": "Info üzenet", "timestamp": "2024-11-14T11:24:58.705018+01:00", "level": "INFO", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 77, "thread_name": "MainThread"}
{"message": "Warning üzenet", "timestamp": "2024-11-14T11:24:58.705018+01:00", "level": "WARNING", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 78, "thread_name": "MainThread"}
{"message": "Error üzenet", "timestamp": "2024-11-14T11:24:58.706032+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 79, "thread_name": "MainThread"}
{"message": "Critical üzenet", "timestamp": "2024-11-14T11:24:58.706032+01:00", "level": "CRITICAL", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 80, "thread_name": "MainThread"}
{"message": "Exception üzenet\nTraceback (most recent call last):\n  File \"h:\\DADY\\rend\\konyvtarak\\2024\\241106_1319_python_logging\\python_logging\\logging_5.py\", line 82, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2024-11-14T11:24:58.706032+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 84, "thread_name": "MainThread"}
{"message": "Debug üzenet", "timestamp": "2024-11-14T11:34:19.701692+01:00", "level": "DEBUG", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 76, "thread_name": "MainThread"}
{"message": "Info üzenet", "timestamp": "2024-11-14T11:34:19.701692+01:00", "level": "INFO", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 77, "thread_name": "MainThread"}
{"message": "Warning üzenet", "timestamp": "2024-11-14T11:34:19.701692+01:00", "level": "WARNING", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 78, "thread_name": "MainThread"}
{"message": "Error üzenet", "timestamp": "2024-11-14T11:34:19.701692+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 79, "thread_name": "MainThread"}
{"message": "Critical üzenet", "timestamp": "2024-11-14T11:34:19.701692+01:00", "level": "CRITICAL", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 80, "thread_name": "MainThread"}
{"message": "Exception üzenet\nTraceback (most recent call last):\n  File \"h:\\DADY\\rend\\konyvtarak\\2024\\241106_1319_python_logging\\python_logging\\logging_5.py\", line 82, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2024-11-14T11:34:19.701692+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 84, "thread_name": "MainThread"}
{"message": "Debug üzenet", "timestamp": "2024-11-14T11:29:29.895798+01:00", "level": "DEBUG", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 76, "thread_name": "MainThread"}
{"message": "Info üzenet", "timestamp": "2024-11-14T11:29:29.895798+01:00", "level": "INFO", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 77, "thread_name": "MainThread"}
{"message": "Warning üzenet", "timestamp": "2024-11-14T11:29:29.895798+01:00", "level": "WARNING", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 78, "thread_name": "MainThread"}
{"message": "Error üzenet", "timestamp": "2024-11-14T11:29:29.895798+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 79, "thread_name": "MainThread"}
{"message": "Critical üzenet", "timestamp": "2024-11-14T11:29:29.895798+01:00", "level": "CRITICAL", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 80, "thread_name": "MainThread"}
{"message": "Exception üzenet\nTraceback (most recent call last):\n  File \"h:\\DADY\\rend\\konyvtarak\\2024\\241106_1319_python_logging\\python_logging\\logging_5.py\", line 82, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2024-11-14T11:29:29.895798+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 84, "thread_name": "MainThread"}
{"message": "Debug üzenet", "timestamp": "2024-11-14T11:47:38.365904+01:00", "level": "DEBUG", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 76, "thread_name": "MainThread"}
{"message": "Info üzenet", "timestamp": "2024-11-14T11:47:38.365904+01:00", "level": "INFO", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 77, "thread_name": "MainThread", "x1": 1, "x2": "ez az x2"}
{"message": "Warning üzenet", "timestamp": "2024-11-14T11:47:38.365904+01:00", "level": "WARNING", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 78, "thread_name": "MainThread", "x1": 1, "x2": "ez az x2"}
{"message": "Error üzenet", "timestamp": "2024-11-14T11:47:38.365904+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 79, "thread_name": "MainThread"}
{"message": "Critical üzenet", "timestamp": "2024-11-14T11:47:38.366913+01:00", "level": "CRITICAL", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 80, "thread_name": "MainThread"}
{"message": "Exception üzenet\nTraceback (most recent call last):\n  File \"h:\\DADY\\rend\\konyvtarak\\2024\\241106_1319_python_logging\\python_logging\\logging_5.py\", line 82, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2024-11-14T11:47:38.366913+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 84, "thread_name": "MainThread"}
{"message": "Debug üzenet", "timestamp": "2024-11-14T11:56:25.280502+01:00", "level": "DEBUG", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 77, "thread_name": "MainThread"}
{"message": "Info üzenet", "timestamp": "2024-11-14T11:56:25.280502+01:00", "level": "INFO", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 78, "thread_name": "MainThread", "x1": 1, "x2": "ez az x2"}
{"message": "Warning üzenet", "timestamp": "2024-11-14T11:56:25.280502+01:00", "level": "WARNING", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 79, "thread_name": "MainThread", "x1": 1, "x2": "ez az x2"}
{"message": "Error üzenet", "timestamp": "2024-11-14T11:56:25.280502+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 80, "thread_name": "MainThread"}
{"message": "Critical üzenet", "timestamp": "2024-11-14T11:56:25.280502+01:00", "level": "CRITICAL", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 81, "thread_name": "MainThread"}
{"message": "Exception üzenet\nTraceback (most recent call last):\n  File \"h:\\DADY\\rend\\konyvtarak\\2024\\241106_1319_python_logging\\python_logging\\logging_5.py\", line 83, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2024-11-14T11:56:25.280502+01:00", "level": "ERROR", "logger": "logging_5", "module": "logging_5", "function": "main", "line": 85, "thread_name": "MainThread"}
